server:
  servlet:
    context-path: /api
  port: 8080

jwt:
  secret:
    access: superMegaSectretJiWiTiAcCeSs123KsuperMegaSectretJiWiTiAcCeSs123KEYEYsuperMegaSectretJiWiTiAcCeSs123KEY
    refresh: giperPuperSectretJeWeTeReFFFReshsuperMegaSectretJiWiTiAcCeSs123KEYshKEYsuperMegaSectretJiWiTiAcCeSs123KEY

security:
  basic:
    enabled: false


spring:
  application:
    name: spring-boot-tasks-manager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weblab4
    username: admin
    password: admin
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher